"""Interactive OAuth token setup for cassette recording.

Usage: python -m tests.setup

1. Opens/prints Yandex OAuth URL
2. Prompts for 7-digit authorization code
3. Exchanges code for tokens via httpx
4. Saves .env.test with tokens
5. Creates .env.test.example (template)
"""

import os
import sys
import webbrowser
from pathlib import Path

import httpx

# Default OAuth credentials (override via env vars)
CLIENT_ID = os.environ.get("YANDEX_CLIENT_ID", "")
CLIENT_SECRET = os.environ.get("YANDEX_CLIENT_SECRET", "")
TOKEN_URL = "https://oauth.yandex.ru/token"
AUTHORIZE_URL = "https://oauth.yandex.ru/authorize"

PROJECT_ROOT = Path(__file__).parent.parent
ENV_TEST = PROJECT_ROOT / ".env.test"
ENV_TEST_EXAMPLE = PROJECT_ROOT / ".env.test.example"


def main() -> None:
    print("=== Yandex.Direct MCP Plugin -- Test Setup ===\n")

    if not CLIENT_ID or not CLIENT_SECRET:
        print("Error: Set YANDEX_CLIENT_ID and YANDEX_CLIENT_SECRET env vars.")
        print("Example: export YANDEX_CLIENT_ID=abc123 YANDEX_CLIENT_SECRET=secret456")
        sys.exit(1)

    # Build auth URL
    auth_url = f"{AUTHORIZE_URL}?response_type=code&client_id={CLIENT_ID}"
    print(f"Open this URL in your browser:\n\n  {auth_url}\n")

    try:
        webbrowser.open(auth_url)
    except Exception:
        pass

    # Get authorization code
    code = input("Enter the 7-digit authorization code: ").strip()
    if not code or not code.isdigit() or len(code) != 7:
        print("Error: Code must be exactly 7 digits.")
        sys.exit(1)

    # Exchange code for tokens
    print("\nExchanging code for tokens...")
    try:
        resp = httpx.post(
            TOKEN_URL,
            data={
                "grant_type": "authorization_code",
                "code": code,
                "client_id": CLIENT_ID,
                "client_secret": CLIENT_SECRET,
            },
            timeout=30,
        )
        resp.raise_for_status()
        token_data = resp.json()
    except httpx.HTTPStatusError as e:
        try:
            error = e.response.json() if e.response else {}
        except (ValueError, AttributeError):
            error = {"error": "http_error", "error_description": str(e)}
        print(f"Error: {error.get('error', 'unknown')} -- {error.get('error_description', '')}")
        sys.exit(1)

    # Save .env.test
    env_content = (
        f"# Auto-generated by python -m tests.setup -- DO NOT COMMIT\n"
        f"YANDEX_OAUTH_TOKEN={token_data['access_token']}\n"
        f"YANDEX_CLIENT_ID={CLIENT_ID}\n"
        f"YANDEX_CLIENT_SECRET={CLIENT_SECRET}\n"
        f"YANDEX_LOGIN={token_data.get('login', '')}\n"
    )
    ENV_TEST.write_text(env_content)
    print(f"Saved: {ENV_TEST}")

    # Create .env.test.example
    example_content = (
        "# Copy to .env.test and fill in your values\n"
        "YANDEX_OAUTH_TOKEN=\n"
        "YANDEX_CLIENT_ID=\n"
        "YANDEX_CLIENT_SECRET=\n"
        "YANDEX_LOGIN=\n"
    )
    ENV_TEST_EXAMPLE.write_text(example_content)
    print(f"Created: {ENV_TEST_EXAMPLE}")

    print("\nSetup complete! Now run: pytest --record")


if __name__ == "__main__":
    main()
